name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - 'v*-mc*' # For v1.3.0-mc26.2, v1.2.1-mc1.21, etc.

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Common Setup
        uses: ./.github/actions/common-setup

      - name: Publish with Gradle
        run: ./gradlew -Pver=${{ github.ref_name }} release

      - name: Upload build results
        uses: actions/upload-artifact@v7
        with:
          name: Release Build
          path: ${{ github.workspace }}/build/libs/

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.workspace }}/build/libs/*
          generate_release_notes: true
          name: ${{ format('Release {0}', github.ref_name) }}
          prerelease: ${{ contains(github.ref_name, '-rc-') }}
          fail_on_unmatched_files: true
          draft: true
